# Generated by Django 5.2.7 on 2025-10-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage_image_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_payment_method',
            field=models.CharField(blank=True, help_text='Actual payment method: card, upi, netbanking, wallet, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_details',
            field=models.JSONField(blank=True, help_text='Additional details like card type, bank name, UPI app, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Razorpay', max_length=50),
        ),
    ]
