# Generated by Django 5.2.7 on 2025-11-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cartitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
