# Generated by Django 5.2.7 on 2025-11-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage_color_name'),
    ]

    operations = [
        # Update payment status choices
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PAID', 'Paid'),
                    ('FAILED', 'Failed'),
                    ('REFUND_PENDING', 'Refund Pending'),
                    ('REFUNDED', 'Refunded')
                ],
                default='PENDING',
                max_length=20
            ),
        ),
        # Add refund tracking fields
        migrations.AddField(
            model_name='order',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_notes',
            field=models.TextField(
                blank=True,
                help_text='Admin notes about refund processing',
                null=True
            ),
        ),
    ]